// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxuxucbzytrhgcfjhkma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4dXh1Y2J6eXRyaGdjZmpoa21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjIxNTIsImV4cCI6MjA2NjY5ODE1Mn0.sKjgw8sMkmzhj_npqte2pJAtlofYB83FF__t3xZAqYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});